# Generated by Django 3.2.18 on 2023-05-13 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demoName', models.CharField(max_length=50)),
                ('demoTime', models.DateTimeField()),
                ('demoResult', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraftType', models.IntegerField()),
                ('coorX', models.DecimalField(decimal_places=3, max_digits=4)),
                ('coorY', models.DecimalField(decimal_places=3, max_digits=4)),
                ('speed', models.DecimalField(decimal_places=3, max_digits=3)),
                ('rank', models.IntegerField()),
                ('recordId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.recording')),
            ],
        ),
    ]
