# Generated by Django 3.2.18 on 2023-05-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0003_remove_recording_demoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='aircraftID',
            field=models.IntegerField(default=1),
        ),
    ]
