# Generated by Django 3.2.18 on 2023-05-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0004_track_aircraftid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='coorX',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='track',
            name='coorY',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='track',
            name='speed',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
